#-------------------------------
# General Site Settings

menu:
# - {name: 'PROJECTS', url: ''}
# - {name: 'ABOUT', url: 'pages/about.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Kit Ko portfolio powered by Jekyll and GitHub Pages'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # Portfolio Jekyll Theme

  This is a personal portfolio theme that I built from the ground up, using the [DevTips Starter Kit](http://devtipsstarterkit.com/) as a foundation for starting, and following closely the amazing tutorial by [Travis Neilson over at DevTips](https://www.youtube.com/watch?v=T6jKLsxbFg4&list=PL0CB3OvPhDA_STygmp3sDenx3UpdOMk7P). You can [check out the demo](lenpaul.github.io/portfolio-jekyll-theme/), and [fork the repository](https://github.com/LeNPaul/portfolio-jekyll-theme/fork), to get started.

contact: >
  # Contact

  You may contact me [through my email](mailto:l.nguyen.paul@gmail.com) or [tweet at me](https://twitter.com/intent/tweet?text=%40paululele) if you have any questions or would like to bring up any issues.

#-------------------------------
# Work Section

projects:
- {name: 'HeartSell', folder: 'proj-1', thumb: 'heartsell_main.jpg', file: 'projects/proj-1.html'}
- {name: 'Customer Management System', folder: 'proj-2', thumb: 'hairlogic_pricelist.jpg', file: 'projects/proj-2.html'}

#-------------------------------
# Contact Section

social:
# - {icon: 'twitter', link: '#'}
- {icon: 'stack-overflow', link: 'https://stackoverflow.com/users/6626508/kitko112'}
- {icon: 'instagram', link: 'https://www.instagram.com/kitko112'}
- {icon: 'github', link: 'https://github.com/kitko112'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/kit-ko-12b656133'}
- {icon: 'medium', link: 'https://medium.com/@kokit'}
- {icon: 'envelope', link: 'mailto:kitko112@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
